name: test_workflow_4
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: download code
        uses: actions/checkout@v4
      - name: Pull some reusable workflow
        uses: ./.workflows/blank3.yml
